### ISSUE TITLE
After the release of Pandas 2.0.0, the abc_analysis() function stopped working

### ISSUE THREAD

**Issue by Richdadua** [viessmann/abc_analysis#2]
After the release of Pandas 2.0.0, the abc_analysis() function stopped working :-(
Here is the error description:
Cell In[33], line 1
    ABC_by_y = abc_analysis(...)

  File ~\miniconda3\envs\ml_ts\lib\site-packages\abc_analysis\abc_analysis.py:246 in abc_analysis
    dictCurve = abc_curve(psData)

  File ~\miniconda3\envs\ml_ts\lib\site-packages\abc_analysis\abc_analysis.py:163 in abc_curve
    y = pd.Series([0]).append(y)

  File ~\miniconda3\envs\ml_ts\lib\site-packages\pandas\core\generic.py:5989 in __getattr__
    return object.__getattribute__(self, name)

AttributeError: 'Series' object has no attribute 'append'

**Comment by ghlt** [comment]
Hi, thank you for the notification. Please update to the latest version 0.1.22, this should solve that issue.
